# Generated by Django 2.0.2 on 2020-10-15 04:14

import datetime
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('article_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('body1', models.TextField()),
                ('body2', models.TextField(blank=True)),
                ('body3', models.TextField(blank=True)),
                ('quote1', models.TextField(blank=True)),
                ('quote2', models.TextField(blank=True)),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
